- type: job
  id: StationTrafficController
  name: job-name-stc
  description: job-description-stc
  playTimeTracker: JobStc
  startingGear: StcGear
  alwaysUseSpawner: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60
  canBeAntag: false
  icon: "JobIconStc" 
  supervisors: job-supervisors-sr
  setPreference: true
  access:
  - Service
  - Maintenance
  - External
  - Frontier
  - StationTrafficController

- type: startingGear
  id: StcGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetectiveGrey
    back: ClothingBackpackStcFilled
    shoes: ClothingShoesColorBlack
    id: StcPDA
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
  innerClothingSkirt: ClothingUniformJumpskirtDetectiveGrey
  satchel: ClothingBackpackSatchelStcFilled
  duffelbag: ClothingBackpackDuffelStcFilled
  messenger: ClothingBackpackMessengerStcFilled # Frontier
