- type: job
  id: Bailiff
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60
  startingGear: BailiffGear
  icon: "JobIconWarden" # Frontier
  supervisors: job-supervisors-sheriff
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Frontier

- type: startingGear
  id: BailiffGear
  equipment:
    head: ClothingHeadHatNfsdBeretBrown # Frontier
    jumpsuit: ClothingUniformJumpsuitNfsdTacCream # Frontier
    back: ClothingBackpackNfsdBrownRadioFilled
    shoes: ClothingShoesBootsNfsdCreamFilled # Frontier
    eyes: ClothingEyesGlassesNfsd # Frontier
    outerClothing: ClothingOuterCoatNfsdFormal # Frontier
    id: BailiffPDA # Frontier
    ears: ClothingHeadsetAltNfsdgreen # Frontier
    belt: ClothingBeltNfsdWebbingFilled # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    pocket2: HoloprojectorNfsd # Frontier
    gloves: ClothingHandsGlovesCombatNfsdCream # Frontier
    neck: ClothingNeckNfsdBadgeWarden # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNfsd # Frontier
  satchel: ClothingBackpackSatchelNfsdBrownRadioFilled # Frontier
  duffelbag: ClothingBackpackDuffelNfsdBrownRadioFilled # Frontier
  messenger: ClothingBackpackMessengerNfsdBrownRadioFilled # Frontier
