- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer" # Frontier
  supervisors: job-supervisors-bailiff
  canBeAntag: false
  accessGroups: # Frontier
  - GeneralNfsdAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNfsdTacBlack # Frontier
    back: ClothingBackpackNfsdBrownRadioFilled
    shoes: ClothingShoesBootsNfsdBrownFilled # Frontier
    eyes: ClothingEyesGlassesNfsd # Frontier
    head: ClothingHeadHatNfsdBeretGreen # Frontier
    outerClothing: ClothingOuterCoatNfsdLongCoat # Frontier
    id: SergeantPDA # Frontier
    ears: ClothingHeadsetAltNfsdbrown # Frontier
    belt: ClothingBeltNfsdFilled # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    gloves: ClothingHandsGlovesCombatNfsdCream # Frontier
    neck: ClothingNeckNfsdBadgeSeniorOfficer # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNfsd # Frontier
  satchel: ClothingBackpackSatchelNfsdBrownRadioFilled # Frontier
  duffelbag: ClothingBackpackDuffelNfsdBrownRadioFilled # Frontier
  messenger: ClothingBackpackMessengerNfsdBrownRadioFilled # Frontier
